---
## 1. create groups
- name: main / Create new groups
  group:
      name: "{{ item.value.groups }}"
  loop: "{{ user_newusers | dict2items }}"

## 2. create new users
- name: main / Create new users
  user:
      name: "{{ item.key))"
      groups: "{{ item.value.groups}}"
      home: "/home/{{ item.key }}"
      password: "{{ item.value.pass }}"
      shell: /bin/bash
      state: present
  loop: "{{ user_newusers | dict2items }}"

## 3. Set Distributed authorized key
- name: main / Distributed authorized key
  authorized_key:
      user: "{{ item.key }}"
      key: "{{ lookup('file', '/home/kuniaki/.ssh/id_rsa.pub') }}"
  loop: "{{ user_newusers | dict2items }}"

## 4. Add system roles
- name: main / Deploy temporary sudoers files
  template:
      dest: "/etc/sudoers.d/{{ item.key }}"
      src: "{{ item.value.priv }}_sudoers.j2"
      trim_blocks: yes # not required. If this is set to True the first newline after a block is removed (block, not variable tag!).
      variable_start_string: {{ # not required. The string marking the beginning of a print statement.
      variable_end_string: }} # not required. The string marking the end of a print statement.
      owner: root
      group: root
      mode: 0400
      validate: 'visudo -c -f %s' # "%s" is dest file 
  loop: "{{ user_newusers | dict2items }}"